### ISSUE TITLE
Categories, tags, Custom fields are not supported on FEE

### ISSUE THREAD

**Issue by chasethenag420** [gios-asu/wp-front-end-editor#20]
Plugin can be enhanced to add or edit categories, tags, Custom fields from FEE.

**Comment by idmontie** [comment]
I wouldn't worry about this too much. The front end editor should really be able editing the content of the post/page.

**Comment by chasethenag420** [comment]
It is working as expected for the scenarios what ever I tried. I couldn't find any other issues as of now.
