### ISSUE TITLE
Links stop working after canceling an edit

### ISSUE THREAD

**Issue by rraub** [gios-asu/wp-front-end-editor#21]
Edit a page and then cancel your edit leaving your changes. The pages links now wont work.

**Comment by chasethenag420** [comment]
Need access to  check this issue on dev site it's working on my local.

**Comment by idmontie** [comment]
Which domain were we testing on? I can't reproduce this bug on the internal sub site.

**Comment by rraub** [comment]
There was an unrelated javascript error on our dev sustainability wordpress site that was causing it to have problems. I can't reproduce it either. I think we can go ahead and close this issue.
