### ISSUE TITLE
Editing pages that aren't actually pages doesn't error

### ISSUE THREAD

**Issue by rraub** [gios-asu/wp-front-end-editor#22]
Instead clicking edit page just does nothing.

**Comment by idmontie** [comment]
Does it produce a JavaScript error?

**Comment by chasethenag420** [comment]
I may need access to dev site for FEE.. I am not able to reproduce in my local machine.

**Comment by rraub** [comment]
Looks like there was a javascript error on our dev site that prevented the rest of the page from loading correctly. Locally its working for me.

related: https://github.com/gios-asu/gios2-php/issues/151
