### ISSUE TITLE
wpautop is always called on the content before edit

### ISSUE THREAD

**Issue by rraub** [gios-asu/wp-front-end-editor#3]
Have a look at https://dcdc.wp.dev.gios.asu.edu/publications/dissertations-and-theses/ 
When your logged into Wordpress, the content on the page is blank. However if your not logged in, the content is there.

This isn't specific to that page, almost any page on that site is missing some content.

**Comment by rraub** [comment]
This is most likely the issue: 
https://github.com/gios-asu/wp-front-end-editor/blob/master/src/class-fee.php#L375

It should check to see if the wpautop filter is currently enabled on the content.

**Comment by idmontie** [comment]
@chasethenag420  Is this still an issue with the latest set of changes?

**Comment by idmontie** [comment]
The line is still there: https://github.com/gios-asu/wp-front-end-editor/blob/master/src/class-fee.php#L433

**Comment by chasethenag420** [comment]
Investigated further and found its not problem with this plugin also wpautop isn't is creating any problem as it is just adding p tag and removing double line breaks. 

https://sustainability.asu.edu/dcdc/publications/dissertations-and-theses/  has same issue and it is displaying blank page on clicking edit via FEE. Problem here is ending div tag is not correct in content after fixing it didn't see any issue.

So probably we might have wrong markup in pages where ever it as blank page.

**Comment by idmontie** [comment]
Document this in the readme just so we know about it and then feel free to close this issue.
