### ISSUE TITLE
Page is blank when attempting to edit

### ISSUE THREAD

**Issue by idmontie** [gios-asu/wp-front-end-editor#31]
Message received: 

> There is an autosave of this post that is more recent than the version below. View the autosave

**Comment by chasethenag420** [comment]
I am not able to reproduce this issue. Can you please let me know which page it is or the scenario?

**Comment by chasethenag420** [comment]
@idmontie Is it same as #3

**Comment by idmontie** [comment]
It might be. I can't remember how to reproduce it. You can close this for now with a `wont fix` label.
