### ISSUE TITLE
integrate 1.1.0 changes

### ISSUE THREAD

**Issue by rraub** [gios-asu/wp-front-end-editor#37]
I've pulled the latest release into our fork on `upstream-changes-1-19-2016` could you test these out?

**Comment by chasethenag420** [comment]
Looks like merge didn't go correctly so the fee.js just got append with  latest 1.1.0 version of fee.js. May be I need to look at changes that came in 1.1.0 and add them to our repo

**Comment by chasethenag420** [comment]
We have removed some code after forking from main repository to get build successful and also modified javascript and php so these two repositories aren't able to merge properly. I add  changes manually.

**Comment by rraub** [comment]
I see that! thanks for catching the problem.
