### ISSUE TITLE
JavaScript error  "No such method remove()"

### ISSUE THREAD

**Issue by chasethenag420** [gios-asu/wp-front-end-editor#8]
Need to find what functionality addNotice is handling what the purpose of remove()..Should some element needs to be removed?

![screenshot from 2015-07-07 09 32 11](https://cloud.githubusercontent.com/assets/10416054/8551392/23aaf0f0-248b-11e5-99a0-e86238af3644.png)

**Comment by idmontie** [comment]
Which file is this? What line number?

**Comment by chasethenag420** [comment]
src/fee.js:352

**Comment by idmontie** [comment]
Use a link next time https://github.com/gios-asu/wp-front-end-editor/blob/master/src/js/fee.js#L352 ;)

**Comment by idmontie** [comment]
The line should most likely be `$notice.remove();`. Not sure though. The code was introduced in this commit: https://github.com/gios-asu/wp-front-end-editor/commit/d7680e0e853ba7ebbb5d2bd4dd3da4ec6e7a51c3
